---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-instance-stnd
    image: python:3-slim-buster
    groups:
      - standaloneinst
  - name: debian-instance-1
    image: python:3-slim-buster
    hostname: debian-instance-1
    networks:
      - name: clusternet
    network_mode: bridge
    groups:
      - group1
  - name: debian-instance-2
    image: python:3-slim-buster
    hostname: debian-instance-2
    networks:
      - name: clusternet
    network_mode: bridge
    groups:
      - group1
  - name: debian-instance-3
    image: python:3-slim-buster
    hostname: debian-instance-3
    networks:
      - name: clusternet
    network_mode: bridge
    groups:
      - group1

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
